apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-corp-traffic
  namespace: corp
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
