apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: team-a
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # Specify the nodePort for external access
  type: NodePort  # Exposes the service on a NodePort
