apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-resource-quota
  namespace: corp  # Apply to the 'corp' namespace or any other namespace you wish to control
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "16Gi"
    limits.cpu: "8"
    limits.memory: "32Gi"
