apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: team-a  # Role applied to the team-a namespace
  name: developer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
